Migrate seccomp profile
Mirantis/cri-dockerd pull request #223
Opened 2023-08-18 17:54 UTC by nwneisen

The method for retrieving the secomp profile path was deprecated in favor of a structure for managing a security profile. This change migrates the code to use the structure rather than the method to get the profile path and do string parsing to determine what profile type is being used. This is now handled using the structure and its methods.

This fixes integration tests related to #198 and moves the pinned integration cri-tools SHA to include tests for these changes.

2023-08-21 18:41 UTC, nwneisen commented
ping @afbjorklund @neersighted

2023-09-05 17:40 UTC, neersighted requested changes

2023-09-05 17:40 UTC, neersighted commented on core/security_context.go
> +	v1 "k8s.io/cri-api/pkg/apis/runtime/v1"
```suggestion
```

Just use the existing `runtimeapi` alias, IMO.

2023-09-05 17:41 UTC, neersighted commented on core/security_context_linux.go
> +	v1 "k8s.io/cri-api/pkg/apis/runtime/v1"
`runtimeapi` would be better for consistency.

2023-09-05 18:02 UTC, neersighted approved these changes

2023-09-05 18:41 UTC, merged